---
title: 'Looking for presenters for this coming year of R-Ladies #LdnOnt'
author: Thea
date: '2018-08-29'
slug: looking-for-presenters-for-this-coming-year-of-r-ladies-ldnont
categories:
  - R-Ladies
tags:
  - rstats
  - rladies
description: ''
---

# Know some R? Share with our team!

As we gear up for our third year of R-Ladies #LdnOnt, we are actively looking for people who would be interested in presenting a tutorial at one of our future meet ups. Our presenters have ranged from relatively new R users all the way up to seasoned R experts; the ideal R-Ladies tutorial presenter would fall anywhere along that continuum!

## Goal: Skill-swapping

Our main goal is to provide an environment in which people interested in learning R can share their skills and learn with other like-minded folks. As such, you don't need to know everything there is to know about R (very few of those people exist, in any case) - you just need to have one topic that you feel you know well enough to be able to share it with a group.

## Anatomy of an R-Ladies #LdnOnt tutorial

Our tutorials typically involve approximately 1 - 1.5 hours of content, which includes a combination of presentation and hands-on exercises. There's no set structure, but if you'd like to check out past tutorials to get a sense, visit our [Past Events page](https://www.meetup.com/rladies-ldnont/events/past/)!

While we typically host our meet ups one the same day of the week (this year will be Thursdays) in the evening (typically 5pm), we are flexible - just mention it!

## A note on what we mean when we say R-"Ladies"

R-Ladies Global "is a worldwide organization whose mission is to promote gender diversity in the R community." While all of our meet ups remain 100% inclusive, we do ask that our presenters identify as non(cis)-males (including but not limited to cis/trans women, trans men, non-binary, genderqueer, agender). That is, while cis men are welcome to attend, we prioritize underrepresented gender identities in our leadership roles. Feel free to scope out the R-Ladies Global [Mission Statement](https://rladies.org/about-us/) and [Code of Conduct](https://rladies.org/code-of-conduct/) for more information. Still have questions? Don't hesitate to email the R-Ladies #LdnOnt leaders, [Thea and Sally](ldnont@rladies.org).

