---
title: "Workshop: Making Science Open With R!"
author: "Thea"
date: 2018-06-06T20:10:13-04:00
categories: ["R-Ladies"]
tags: ["R Markdown", "rstats", "blogdown"]
---

<center>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">🎉 Next meet up: Making Science Open with R! Led by <a href="https://twitter.com/Monsauce?ref_src=twsrc%5Etfw">@monsauce</a>. 🎉<br>Learn about how <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a>, <a href="https://twitter.com/hashtag/rmarkdown?src=hash&amp;ref_src=twsrc%5Etfw">#rmarkdown</a>, and Google Sheets can work together for you to create a reproducible workflow.<br><br>Join us on June 26 at 5pm at the <a href="https://twitter.com/LondonPublicLib?ref_src=twsrc%5Etfw">@LondonPublicLib</a>! All are welcome. <a href="https://t.co/fZN2Atoxv6">https://t.co/fZN2Atoxv6</a> <a href="https://t.co/C6HjqCYbG2">pic.twitter.com/C6HjqCYbG2</a></p>&mdash; R-Ladies LdnOnt (@RLadiesLdnOnt) <a href="https://twitter.com/RLadiesLdnOnt/status/1004499488055046144?ref_src=twsrc%5Etfw">June 6, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

</center>

# Details

Join us for our last meet up until the fall! We are thrilled to have [Monica Granados](https://twitter.com/monsauce) back with us again to close out our second year! Monica comes with a wealth of experience using R and teaching others to use it. She's led numerous tutorials, many of which you can check out via the links below.

This meet up will focus on **Open Science**:


Founded on the principle science should not be limited by your occupation, race, nationality or economic status, working in the open makes science more accessible by making methods, code, results and knowledge available to anyone, anywhere in the world. Imagine if every analysis you ever conduct from now on could be reproduced by anyone around the world. Or a method that gives you the power to integrate new data seamlessly complete with figures. In this workshop, we will be covering how to work in the open using R, R Markdown and Google Sheets. These three platforms allow us to host data, analyze, visualize data in one reproducible workflow. At the end of the workshop we will also discuss the wider movement of open science, how it is helping breakdown economic barriers in science and how you can contribute.

Learn more about Monica by checking out her...

- [Website](http://descienceblog.tumblr.com/) 
- [Twitter](https://twitter.com/monsauce)
- [R tutorials](http://qcbs.ca/wiki/r)

As per usual, we will head to Milo's afterwards to celebrate, chat, and all in all just enjoy each other's company.