---
title: So long, farewell, and stay tuned!
author: Thea
date: '2019-05-31'
slug: so-long-farewell-and-stay-tuned
categories:
  - RLadies
  - workshops
tags:
  - ldnont
  - lndont
  - meetup
  - R
  - rladies
description: ''
---

<center>
<iframe src="https://giphy.com/embed/lD76yTC5zxZPG" width="480" height="352" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/the-end-thats-all-folks-lD76yTC5zxZPG">via GIPHY</a></p>
</center>

Thus concludes this season of R-Ladies #LdnOnt! Thank you to Jaky for leading us through our last workshop together, and to all of you who came out to these things over the last two and a half years. Workshop materials are posted in the usual places (website, GitHub, Drive).

Some news that I've spoken about a bit in person but not in any official capacity yet: Sally and I are stepping down as organizers. I'll be leaving London in July, and Sally's got a lot on her plate this year with PhD and R-baby. We don't currently have an active plan in place for somebody to take over the helm, though I have spoken with a few of our members (`r emo::ji("wave")` you know who you are!), and know that there are some who have expressed interest in being involved in a *community-run* chapter.
This will be the plan we'll be exploring going forward: perhaps a co-op or rocur style group; the details remain to be seen. Importantly, if you have any interest in getting involved with the R-Ladies chapter leadership in any way next year, aboslutely reach out to me (ldnont at rladies dot org). 


<center>

### Assemble the team!

<iframe src="https://giphy.com/embed/t6f2bNAjx7Bio" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/t6f2bNAjx7Bio">via GIPHY</a></p>
</center>


I have a lot of other feelings to speak of, but I fear getting started writing them down right here and now would run the risk of me getting rambly and nostalgic, so I'm going to save my final thoughts on R-Ladies for another post in a couple weeks.

<center>
<iframe src="https://giphy.com/embed/RVNxE5ZDyBufe" width="480" height="316" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/crying-glee-happy-RVNxE5ZDyBufe">via GIPHY</a></p>
</center>

I'll send and update later on in the summer about what the future of R-Ladies #LdnOnt looks like!


