---
title: Spring 2019 Workshops Announced!
author: ''
date: '2019-02-22'
slug: spring-2019-workshops-announced
categories: []
tags: []
description: ''
---

<center>
<iframe src="https://giphy.com/embed/9MJ7eHnB9R7HmUDq0B" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/rupaulsdragrace-episode-11-rupauls-drag-race-9MJ7eHnB9R7HmUDq0B">via GIPHY</a></p>
</center>


# Spring lineup

We are PUMPED to announce a series of #RLadies #LdnOnt workshops for the upcoming season! All workshops will be held the last Thursday of the month at 5:30 p.m. at the London Public Library downtown.

- March 28: Heatmaps & Pointmaps using ggmap led by Rebecca Henderson
- April 25: Dissertating in RMarkdown led by Thea Knowles
- May 30: TBD led by Jaky Kueper

Watch this space for more details as meet up information is announced!

# Quick deets!

- `r emo::ji("question")` **What is R-Ladies?** A low-key get together for people interested in using and learning more about R, a powerful statistical software program. We meet about once a month to feature different topics and speakers. 
- `r emo::ji("clock12")` **When:** Last Thursdays of the month from 5:30 - 7:30
- `r emo::ji("round_pushpin")`**Where:** London Public Library, Central Branch (251 Dundas, right downtown). We will be in the Lawson Room on the first floor, across from the main library entrance (formerly known as the Richmond Room).
-  `r emo::ji("moneybag")`**Cost:** All our meet ups are free, and always will be!
-  `r emo::ji("+1")`**Sounds good, where do I sign up?** [**RSVP**](https://www.meetup.com/rladies-ldnont/) for the workshops as they're announced at our MeetUp page